# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.dockerfile

tasks:
  - name: Build clad with LLVM-10
  - init: |
      ./scripts/install_dependencies.sh 10
      ./scripts/build_clad.sh 10
      exit 0
  

