# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# image:
#   file: .gitpod.dockerfile

tasks:
  - init: sudo apt install clang-10 libclang-10-dev llvm-10-tools llvm-10-dev
    command: echo 'install llvm-10'
  

