# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# image:
#   file: .gitpod.dockerfile

tasks:
  - init: export PATH=${PATH}:/workspace/clad/scripts
    command: echo 'install llvm-10'
    env:
      PATH: "${PATH}:/workspace/clad/scripts"
  

