version: 2

sphinx:
  configuration: docs/userDocs/source/conf.py
  builder: html

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  apt_packages:
    - clang-14
    - cmake
    - libclang-14-dev
    - llvm-14-dev
    - llvm-14-tools
